// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6HZn1zbPC5y_gB5crViwX1j2sA1DlxQg',
    appId: '1:753606427943:web:66b48ce30e5503917cd502',
    messagingSenderId: '753606427943',
    projectId: 'point-of-sale-247a7',
    authDomain: 'point-of-sale-247a7.firebaseapp.com',
    storageBucket: 'point-of-sale-247a7.firebasestorage.app',
    measurementId: 'G-5HPHJNHQ1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsty4AVQICLcJTUF3ECyH4M9AnK3cwNm0',
    appId: '1:753606427943:android:7e186f44dd7abc977cd502',
    messagingSenderId: '753606427943',
    projectId: 'point-of-sale-247a7',
    storageBucket: 'point-of-sale-247a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9VXgK8FLGmHPlEJrCsnxo27UtX34QjuU',
    appId: '1:753606427943:ios:7ea22edd43c0939c7cd502',
    messagingSenderId: '753606427943',
    projectId: 'point-of-sale-247a7',
    storageBucket: 'point-of-sale-247a7.firebasestorage.app',
    iosBundleId: 'com.example.pos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9VXgK8FLGmHPlEJrCsnxo27UtX34QjuU',
    appId: '1:753606427943:ios:7ea22edd43c0939c7cd502',
    messagingSenderId: '753606427943',
    projectId: 'point-of-sale-247a7',
    storageBucket: 'point-of-sale-247a7.firebasestorage.app',
    iosBundleId: 'com.example.pos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6HZn1zbPC5y_gB5crViwX1j2sA1DlxQg',
    appId: '1:753606427943:web:5cd9de1d856bebe47cd502',
    messagingSenderId: '753606427943',
    projectId: 'point-of-sale-247a7',
    authDomain: 'point-of-sale-247a7.firebaseapp.com',
    storageBucket: 'point-of-sale-247a7.firebasestorage.app',
    measurementId: 'G-Q9LXE56JKS',
  );
}
